[package]
name = "crankshaft"
version = "0.1.0"
authors = ["Ferdia McKeogh <ferdia@mckeogh.tech>"]
edition = "2018"

[dependencies]
cortex-m = "0.5.8"
stm32f1xx-hal = { version = "0.2.1", features = ["stm32f103", "rt"] }
cortex-m-rt = "0.6.7"
panic-semihosting = "0.5.1"
cortex-m-semihosting = "0.3.2"
cortex-m-rtfm = "0.4.2"
enc28j60 = "0.2.1"
embedded-hal = "0.2.2"
heapless = "0.4.2"
jnet = { git = "https://github.com/japaric/jnet", rev = "df96b408049ca952ad7844d6552e87cf8fc18d2a" }
