[package]
name = "crankshaft"
version = "0.1.0"
authors = ["Ferdia McKeogh <ferdia@mckeogh.tech>"]
edition = "2018"

[dependencies]
cortex-m = "0.5.8"
nb = "0.1.1"
cortex-m-rt = "0.6.7"
stm32f4xx-hal = { version = "0.3.0", features = ["rt", "stm32f411"] }
panic-itm = "0.4.0"
# cortex-m-rtfm = "0.3.1"
enc28j60 = { git = "https://github.com/japaric/enc28j60.git", rev = "694e21f" }
heapless = "0.4.1"
m = "0.1.1"
mfrc522 = "0.2.0"
serde_derive = "1.0.87"
cortex-m-rtfm = "0.4.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dependencies.byteorder]
default-features = false
version = "1.3.1"

[dependencies.cobs]
default-features = false
version = "0.1.3"

[dependencies.crc16]
default-features = false
version = "0.4.0"

[dependencies.either]
default-features = false
version = "1.5.0"

[dependencies.jnet]
git = "https://github.com/japaric/jnet"
rev = "df96b408049ca952ad7844d6552e87cf8fc18d2a"

[dependencies.serde]
default-features = false
version = "1.0.87"

[dependencies.serde-json-core]
git = "https://github.com/japaric/serde-json-core"
rev = "6f12b77c1ffeae167989fe06e0d8b15978bd6d18"
